58 spar annotation
Virtual-Viking-Longship/Ship-Annotations pull request #63
Opened 2024-12-05 02:17 UTC by ellaparke

2024-12-05 17:26 UTC, apjmason requested changes
@ellaparke after reading this, I think we should change the head word to "tacking-boom" and make this an annotation for beitiass in particular, not just ass in general. We can define general "spar" as ass in the definition, but it's the tacking-boom that you are most concerned with here and also what we have modeled on our ship in VR. 

Can you make those changes, referencing the entries for tacking boom on the [Ship Terminology spreadsheet](https://docs.google.com/spreadsheets/d/1SdY51aqCSdwGvNHDfiLJjZuJCulogexdHsut1iaPg-M/edit?gid=1259887355#gid=1259887355)?

2024-12-05 17:33 UTC, apjmason requested changes

2024-12-05 17:33 UTC, apjmason commented on annotations/spar.md
> +  Use of the spar reduces strain on the side of a ship, by spreading the pressure from the sail over to the opposite side, where the forces can be spread over several frames (Bishcoff, Vibeke). 2). T
This is well written, but the Imer 2004 and Andersen and Andersen references are not included below
```suggestion
  Use of the spar reduces strain on the side of a ship, by spreading the pressure from the sail over to the opposite side, where the forces can be spread over several frames (Bishcoff 2017, 2). The use of the beitiáss is also known from iconographic sources as on the Gotland picture stone from Klinte Hunninge and from ethnographic boats from northwestern Iceland (Imer 2004, 58; Andersen and Andersen
```

2024-12-05 17:33 UTC, apjmason commented on annotations/spar.md
> +  Hale, John R. “The Viking Longship.” Scientific American 278, no. 2 (1998): 56–63.
Add a space between references to preserve formatting.

Add Imer 2004 and Andersen and Andersen sources

2024-12-05 18:55 UTC, ellaparke reviewed
Changes have been made except for the one of the sources as I cannot find it.

2024-12-18 16:44 UTC, apjmason approved these changes
Updated and now surpassed

2024-12-18 16:47 UTC, merged