39 anchor
Virtual-Viking-Longship/Ship-Annotations pull request #66
Opened 2024-12-05 16:23 UTC by Mothy75

(1) added new image (not sure about citation) (2) added what it was used for section-need to write more.

2024-12-19 21:35 UTC, apjmason requested changes
Looks good! Made some edits and suggestions for image replacement

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +_**akkeri** n., pl. akkerum_ (Old Norse) [citations: [prose](https://onp.ku.dk/onp/onp.php?o1281)/[poetry](https://lexiconpoeticum.org/m.php?p=lemma&i=2907)]
```suggestion
_**akkeri**_ n., pl. _akkeri_ (Old Norse) [citations: [prose](https://onp.ku.dk/onp/onp.php?o1281)/[poetry](https://lexiconpoeticum.org/m.php?p=lemma&i=2907)]  
```

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +  ![anchor from Ladby ship](../images/Anchor_Ladby.png)
We don't have permission to use this image. I need to take them out of the repo.

We should maybe use [the one from Oseberg here](https://www.nb.no/items/URN:NBN:no-nb_digibok_2019111248002?page=335) and maybe also the separate image of the stock from Nicolaysen Plate IV Figure 17

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +Anchors were critical for controlling and docking Viking ships, especially in storms or raids. Anchors were used when camping aboard a ship at night or when preparing for stealthy attacks (Jesh 166).
```suggestion
Anchors were critical for controlling and docking Viking ships, especially in storms or during raids. Anchors were used when camping aboard a ship at night or when preparing for stealthy attacks (Jesch 166). It is believed that Viking Age anchors were made of iron or a composite of wood, stone, and rope. The former would have been expensive and used on large ships while the latter would be more affordable and used on small ships (Crumlin-Pederson, 146). 
```

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +  Jesch, Judith. _Ships and Men in the Late Viking Age: The Vocabulary of Runic Inscriptions and Skaldic Verse._ NED-New edition. Woodbridge, Suffolk, UK ; Rochester, NY:
```suggestion
  Jesch, Judith. _Ships and Men in the Late Viking Age: The Vocabulary of Runic Inscriptions and Skaldic Verse._ (Boydell & Brewer, 2001). https://www.jstor.org/stable/10.7722/j.ctt163tb4f
```

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +  Jesch, Judith. _Ships and Men in the Late Viking Age: The Vocabulary of Runic Inscriptions and Skaldic Verse._ NED-New edition. Woodbridge, Suffolk, UK ; Rochester, NY:
Moving to one line and removing place of publication, since no longer advised in Chicago 18

2024-12-19 21:35 UTC, apjmason commented on annotations/anchor.md
> +Boydell & Brewer, 2001. https://www.jstor.org/stable/10.7722/j.ctt163tb4f.
```suggestion
```

2024-12-19 21:35 UTC, apjmason commented on images/Anchor_Prigny.png
Oh, this image could work! Is it CC licensed? Needs to be linked above and given the correct credit

2024-12-20 15:44 UTC, Mothy75 commented on images/Anchor_Prigny.png
Yes it is, I will add the link and credit now!

2024-12-20 18:10 UTC, apjmason commented
@Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad

2024-12-20 18:19 UTC, Mothy75 commented
> @Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad

@apjmason from the wikipedia commons https://commons.wikimedia.org/wiki/File:Ancre_viking_Prigny_0033sc.jpg - how best should I cite it? something like 'Wikipedia Commons, under the GNU Free Documentation License'?

2024-12-20 18:26 UTC, apjmason commented
> > @Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad
> 
> @apjmason from the wikipedia commons https://commons.wikimedia.org/wiki/File:Ancre_viking_Prigny_0033sc.jpg - how best should I cite it? something like 'Wikipedia Commons, under the GNU Free Documentation License'?

We have a couple of other examples of that in the main branch. See [Reef](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/annotations/mast.md) for instance. Can you also edit the images_sources file in this branch to add your image and it's citation, similar to how we've done others in the [main branch version](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/images/images_sources.md)?

2024-12-20 18:28 UTC, apjmason commented
> > > @Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad
> > 
> > 
> > @apjmason from the wikipedia commons https://commons.wikimedia.org/wiki/File:Ancre_viking_Prigny_0033sc.jpg - how best should I cite it? something like 'Wikipedia Commons, under the GNU Free Documentation License'?
> 
> We have a couple of other examples of that in the main branch. See [Reef](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/annotations/mast.md) for instance. Can you also edit the images_sources file in this branch to add your image and it's citation, similar to how we've done others in the [main branch version](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/images/images_sources.md)?

Copy the attribution from the wikimedia page you linked under the Use this File on the web icon 
![image](https://github.com/user-attachments/assets/0ec8555f-0891-4561-a114-4cded1a45a9f)

2024-12-20 18:29 UTC, apjmason commented
> > > @Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad
> > 
> > 
> > @apjmason from the wikipedia commons https://commons.wikimedia.org/wiki/File:Ancre_viking_Prigny_0033sc.jpg - how best should I cite it? something like 'Wikipedia Commons, under the GNU Free Documentation License'?
> 
> We have a couple of other examples of that in the main branch. See [Reef](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/annotations/mast.md) for instance. Can you also edit the images_sources file in this branch to add your image and it's citation, similar to how we've done others in the [main branch version](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/images/images_sources.md)?

Copy the attribution from the wikimedia page you linked under the Use this File on the web icon 
![image](https://github.com/user-attachments/assets/1fa974c5-d95c-4f4a-ac82-9bcb4f5945db)

2024-12-20 18:47 UTC, Mothy75 commented
> > > > @Mothy75 Where did you get the image of the anchor? We either need a citation or to use public domain ones from Oseberg or Gokstad
> > > 
> > > 
> > > @apjmason from the wikipedia commons https://commons.wikimedia.org/wiki/File:Ancre_viking_Prigny_0033sc.jpg - how best should I cite it? something like 'Wikipedia Commons, under the GNU Free Documentation License'?
> > 
> > 
> > We have a couple of other examples of that in the main branch. See [Reef](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/annotations/mast.md) for instance. Can you also edit the images_sources file in this branch to add your image and it's citation, similar to how we've done others in the [main branch version](https://github.com/Virtual-Viking-Longship/Ship-Annotations/blob/main/images/images_sources.md)?
> 
> Copy the attribution from the wikimedia page you linked under the Use this File on the web icon ![image](https://private-user-images.githubusercontent.com/10544799/397831167-0ec8555f-0891-4561-a114-4cded1a45a9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjA1MTAsIm5iZiI6MTczNDcyMDIxMCwicGF0aCI6Ii8xMDU0NDc5OS8zOTc4MzExNjctMGVjODU1NWYtMDg5MS00NTYxLWExMTQtNGNkZWQxYTQ1YTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE4NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMGQ0MzhjNmJiNjgyYzIzOGE5NGU4NDViZjA4YzZmNDRlOTNiZTViNjkwNzQ3MDBiY2RkMzEyMDQ5YWQzMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7XqibGlwTA6Tb5MFp1xzO1iZxYKDDUTz7bhR347qOLc)

@apjmason thanks for the edits! I should have revised the image attribution now. Would you mind reminding me how to move my anchor image from the anchor branch to the main one?

2024-12-20 18:53 UTC, apjmason commented
I'll handle that when I approve the PR and merge. Thanks!

2024-12-21 16:05 UTC, apjmason approved these changes

2024-12-21 16:08 UTC, merged